Show/upload test results even when ESLint step fails

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -26,9 +26,9 @@ jobs:
         run: npm ci --no-fund
       - name: Run ESLint
         run: npm run security:eslint
-        continue-on-error: true
       - name: Upload analysis results to GitHub
         uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure() # Run this step even if previous step failed.
         with:
           sarif_file: eslint-results.sarif
           wait-for-processing: true
@@ -66,6 +66,7 @@ jobs:
         run: npm run test
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v1.6
+        if: success() || failure() # Run this step even if previous step failed.
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -91,3 +92,4 @@ jobs:
         run: npm run test
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v3
+        if: success() || failure() # Run this step even if previous step failed.
